/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    java
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.opencsv:opencsv:5.8")  
    testImplementation("junit:junit:4.13.2")
}

application {
    mainClass.set("com.wabradshaw.bannerbeasts.balancer") 
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
